server:
  port: 8601
spring:
  application:
    name: spring-cloud-consul-producer
  cloud:
    consul:
      discovery:
        #注册到consul的服务名称
        serviceName: tyrael-service-producer
      host: localhost
      port: 8500

